// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Seek.EF;

#nullable disable

namespace Seek.EF.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250730113833_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Seek.Core.Models.auth_model", b =>
                {
                    b.Property<int>("Ud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ExpiresIn")
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hashed_Refresh_Token")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Ud");

                    b.HasIndex("HashedLogin")
                        .IsUnique();

                    b.ToTable("FK_Auth", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
